Notify only after 3 failures
TalalChaudhry/slack-plugin pull request #1
Opened 2017-01-26 08:31 UTC by TalalChaudhry

2017-01-26 09:57 UTC, mfrawley requested changes

2017-01-26 09:57 UTC, mfrawley commented on src/main/java/jenkins/plugins/slack/ActiveNotifier.java
> +                    && count == N
count will only ever reach N-1 due to the for loop constraints

2017-01-26 09:57 UTC, mfrawley commented on src/main/java/jenkins/plugins/slack/SlackNotifier.java
> +    public int getNumberOfFailuresAfterToNotify() {
getFailureNotificationThreshold would be better

2017-01-26 09:57 UTC, mfrawley commented on src/main/java/jenkins/plugins/slack/ActiveNotifier.java
> +        int N = notifier.getNumberOfFailuresAfterToNotify();
call it failureNotificationThreshold

2017-01-26 09:57 UTC, mfrawley commented on src/main/java/jenkins/plugins/slack/SlackNotifier.java
> +            return ""; //$NON-NLS-1$
What does this comment mean?

2017-01-26 09:57 UTC, mfrawley commented on src/main/java/jenkins/plugins/slack/SlackNotifier.java
> +        this.notifyFailureAfterNTimess = notifyFailureAfterNTimess;
s/Timess/Times/g

2017-01-26 10:21 UTC, TalalChaudhry commented on src/main/java/jenkins/plugins/slack/ActiveNotifier.java
> +                    && count == N
Right. thanks

2017-01-26 10:21 UTC, TalalChaudhry commented on src/main/java/jenkins/plugins/slack/SlackNotifier.java
> +            return ""; //$NON-NLS-1$
Ah sorry. I forgot to remove this. Was for some other idea that I ditched

2017-01-26 13:05 UTC, mfrawley approved these changes

2017-02-13 14:18 UTC, TalalChaudhry commented
@mfrawley  @KlausTrainer  PTAL

Added feature to notifyBackToNormalAfterNFailures as well!

2017-02-14 12:18 UTC, TalalChaudhry commented
https://github.com/Jimdo/data-documentation/issues/143#issuecomment-279692692

2017-02-14 12:32 UTC, mfrawley approved these changes
LGTM

2017-02-16 09:04 UTC, merged